### ISSUE TITLE
Error while trying to add a suggestion with a quotation mark (or any special character)

### ISSUE THREAD

**Issue by LeaChemoul** [ether/ep_comments_page#175]
## Context

* **OS**: Intel Mac OS X 10_14_6
* **Browser** : Mozilla/5.0, Chrome/86.0.4240.198
* **Etherpad** version: 1.8.6
* **ep_comments_page** version: 0.1.44

## Behavior

When adding a quote in a suggestion (`"` or `'`) an error occurs saying `Unexpected token in JSON at position`.
Seems like others special characters are having troubles too. (Tested : https://www.computerhope.com/jargon/s/specchar.htm )

## Steps to reproduce

Add a comment with a suggestion that contains quote mark

<img width="500" alt="Capture d’écran 2020-12-10 à 09 51 34" src="https://user-images.githubusercontent.com/34442368/101749511-2007fb00-3ace-11eb-80e2-0370a966019b.png">

## Failure Logs

When opening developer tools, console displays this error. It says that a token near 'F' is invalid. 

```
VM361:1 Uncaught SyntaxError: Unexpected token F in JSON at position 50
    at JSON.parse (<anonymous>)
    at Object.html10n.translateNode (html10n.js?v=54405fc9:1)
    at Object.html10n.translateElement (html10n.js?v=54405fc9:1)
    at Object.localize (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:41)
    at EpComments.insertComment (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:12443)
    at HTMLSpanElement.eval (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:9526)
    at Function.each (ace2_common.js?callback=require.define&v=54405fc9:27)
    at m.fn.init.each (ace2_common.js?callback=require.define&v=54405fc9:27)
    at EpComments.collectComments (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:9249)
    at r.eval (eval at j (require-kernel.js?v=54405fc9:10), <anonymous>:5:18760)
```

**Further investigation** : No problems when adding a simple comment with a quote.

## Failure image

<img width="862" alt="Capture d’écran 2020-12-10 à 09 51 46" src="https://user-images.githubusercontent.com/34442368/101750200-fac7bc80-3ace-11eb-848c-fbe1e2b0a2e1.png">

Then comment is broken and can't be displayed.

<img width="379" alt="Capture d’écran 2020-12-10 à 09 52 43" src="https://user-images.githubusercontent.com/34442368/101749738-5f364c00-3ace-11eb-9b48-d447b9cef6e4.png">

**Special note**
Thank you for all you work on this project 😄

**Comment by JohnMcLear** [comment]
Confirmed.  I'm concerned this could be an XSS too.  The ``changeTo`` variable is written into the element really weirdly..  I think it mostly needs a ``Security.escapeHTML`` but then also why is ``i10n`` being passed over it?  Too weird..  Needs more than the 5 minutes I had to look at it today.

**Comment by LeaChemoul** [comment]
That's really weird, I was wondering the same for the i10n. Why are you not using the same logic between basic comments and suggestion inputs ?

That's a real problem for me because I'm currently using etherpad for production and it is breaking my pads. 
Does your temporary patch fix future inserted special characters and previous broken pads ?

Thank you very much for your time 😄

**Comment by JohnMcLear** [comment]
I don't have time to go into depth on this.  It will work in production and it fixes historical issues

**Comment by LeaChemoul** [comment]
It's already great to have put a temporary fix. Thanks for your time and all your contribution to etherpad that's amazing !

---- 
I see that the correction is effective only in private browsing. It's just a problem with the `cache` since when I empty my cache everything works fine but I don't want to force users to have to go through this step (some are not comfortable with a computer). My cache is at `MAX_AGE = 0` but I have the feeling that the old javascript files are still loaded.

Do you have any advice for me or do you know how to do it? 
I encounter this problem with all the fixes. 

Thank you for your help !
