### ISSUE TITLE
ep_comments_page not working with etherpad-lite 1.8.7

### ISSUE THREAD

**Issue by techware01** [ether/ep_comments_page#177]
##  Problem
After updating to the latest etherpad-lite release commenting is not possible anymore. When pressing the plus button for commenting nothing happens. Also there is no visible feedback for pressing the button on the screen or in the console. 
Only after loading a pad the develeoper console in the browser shows the following ep_comments_page related errors:
```
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/postAceInit': Error: The module at "ep_comments_page/static/js/timeFormat" does not exist. ace2_common.js:62:961
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceAttribsToClasses': Error: The module at "ep_comments_page/static/js/timeFormat" does not exist. ace2_common.js:62:961
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceEditorCSS': Error: The module at "ep_comments_page/static/js/timeFormat" does not exist. ace2_common.js:62:961
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceEditEvent': Error: The module at "ep_comments_page/static/js/timeFormat" does not exist. ace2_common.js:62:961
Failed to load 'ep_comments_page/static/js/index' for 'ep_comments_page/comments_page/client_hooks/aceInitialized': Error: The module at "ep_comments_page/static/js/timeFormat" does not exist. ace2_common.js:62:961
```

## Installed Version
etherpad-lite: 1.8.7
ep_comments_page: 0.1.46

## Installed Plugins
ep_align
ep_author_hover
ep_comments_page
ep_etherpad-lite
ep_font_color
ep_headings2
ep_table_of_contents

**Comment by JohnMcLear** [comment]
Did you try uninstall the plugin and reinstall it?

**Comment by techware01** [comment]
Reinstalled now using: 
``` 
npm uninstall ep_comments_page
npm install ep_comments_page
``` 
and restarted the service. But still nothing happens.

**Comment by JohnMcLear** [comment]
Try clearing your browser cache..

I just did a clean install, the two commands above and it worked fine.

Also check you **don't** have ``package.json`` and ``package-lock.json`` in the root folder of Etherpad

**Comment by techware01** [comment]
Ok after clearing the browser cache it's working now. Thank you!
Why should there be no `package.json` and `package-lock.json' in the root folder? I have both of them there.

**Comment by meaz** [comment]
I would also be much interested in the answer to @techware01 questions...

**Comment by JohnMcLear** [comment]
Things changed.  Your root package files should contain lint and plugins, just not core deps

**Comment by meaz** [comment]
and where should they be then?
