### ISSUE TITLE
Outdate version by npm

### ISSUE THREAD

**Issue by Yaco** [ether/ep_comments_page#185]
Hi!
just wanna report that when I tried to install this plugin using the official instructions, the command ```npm install ep_comments_page``` I got an older version. Needed to install using git to get the version shows in the main thumbnail on the README.

I think the npm package is outdated?

**Comment by JohnMcLear** [comment]
The package should auto publish once lint tests pass.  My guess is that it needs linting up.

**Comment by JohnMcLear** [comment]
Looks like it was due to a change in the eslint config, I'm pushing some more lint fixes now so hopefully a new version will get released.

**Comment by JohnMcLear** [comment]
Should auto publish a fix now :)

**Comment by Yaco** [comment]
Hi John! osrry to bother again with this, but seems is not fixed.

Just installed it again by npm and still old version. In package.json of the plugin it says: ``` "version": "0.0.35",```

My npm version is 6.14.4.

Any clue?

**Comment by JohnMcLear** [comment]
Are you sure you are installing the right plugin?

https://www.npmjs.com/package/ep_comments_page

**Comment by Yaco** [comment]
I did: ```npm install ep_comments_page```. Below is the full output of the command and the version detail:

```
$ npm install ep_comments_page

> wd@1.12.1 install /home/etherpad/etherpad-lite/node_modules/ep_etherpad-lite/node_modules/wd
> node scripts/build-browser-scripts

npm WARN etherpad-lite No repository field.
npm WARN etherpad-lite No license field.

+ ep_comments_page@0.0.35
added 295 packages from 553 contributors, removed 296 packages, updated 22 packages and audited 1139 packages in 17.965s

65 packages are looking for funding
  run `npm fund` for details

found 11 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

$ head node_modules/ep_comments_page/package.json 
{
  "description": "Adds comments on sidebar and link it to the text.  Support for Page View, requires ep_page_view",
  "name": "ep_comments_page",
  "version": "0.0.35",
  "author": {
    "name": "Nicolas Lescop",
    "email": "limplementeur@gmail.com"
  },
  "contributors": [
    {
```

**Comment by Yaco** [comment]
However, I am also getting this:

```
$ npm view ep_comments_page version
0.1.48
```
mmm?
