### ISSUE TITLE
vanishing comments

### ISSUE THREAD

**Issue by zzkt** [ether/ep_comments_page#191]
After a recent upgrade, looks like old comments are no longer visible and new comments can't be added. Using comments_page 0.1.54 and etherpad version 1.8.11 (Git sha: ad84c8a)

**Comment by JohnMcLear** [comment]
From what version of ep_comments?

**Comment by zzkt** [comment]
The comments are still in the db, they are exported as expected via /export/html but aren't displayed on the pad...

**Comment by zzkt** [comment]
I've updated etherpad & the plugin and the comments have now reappeared, but I had to manually reinstall tinycon. 

Can't see anything obviously different in the stored comments using either the `pad:id` or `comments:id` keys...
