### ISSUE TITLE
Suggestion texts show %20 for space (also applies for other special characters)

### ISSUE THREAD

**Issue by SVerena** [ether/ep_comments_page#211]
**Describe the bug**
When adding a comment in English with a suggested change, any "special" character is shown in its percent-encoded form. For example a space is shown as %20, a bracket as %28.

**To Reproduce**
I added a comment while the pad was set English language with a suggested change.
I also noticed it in other languages like Spanish or French.
Interestingly enough, in German the suggested change was not shown at all. (see second screenshot)

**Expected behavior:**
normal text without encoded characters

**Screenshot:**
![image](https://user-images.githubusercontent.com/90773676/136032662-155d4310-3a4a-4e36-b1eb-2b0000785a92.png)
![image](https://user-images.githubusercontent.com/90773676/136036157-792adb1c-dd23-4f7a-b607-52c485d2bdb0.png)

**Desktop** (please complete the following information):

OS: Windows 10
Browser: chrome
Version: 93

If you need more information, let me know.
Thank you!
Verena

**Comment by JohnMcLear** [comment]
I imagine we show the suggested change as uri encoded and it needs decoding.  This is probably to avoid XSS / injections.

**Comment by JohnMcLear** [comment]
It'd be cool to see test coverage for this, if you refer to other tests it should be pretty easy to make the test and that makes writing a fix a much easier job!

**Comment by SVerena** [comment]
sure, what do you need? more detailed steps to reproduce? more screenshots? 
I can also try to find out which other characters and languages are affected.

**Comment by JohnMcLear** [comment]
If you can write a test IE https://github.com/ether/ep_comments_page/tree/main/static/tests/frontend/specs that would be great!

**Comment by iu0v1** [comment]
Doubled.

Text in Ukrainian look like this:
![chrome_5nSdMLxRdH](https://user-images.githubusercontent.com/1669027/141594373-25d70117-bbe4-4770-a4e8-9c009fb6837a.png)
