### ISSUE TITLE
Live editing ep_comment code 

### ISSUE THREAD

**Issue by riedelcastro** [ether/ep_comments_page#242]
Hi,

thanks to previous replies here, I have now cloned `ep_comments_page` into the `node_module` folder of etherpad. This seems to work in that I can make changes to the plugin that get reflected in the editor instance--but only after I re-run it. Is there a way of doing "live edits" in the code that affect the instance without re-running?

Thank you!

**Comment by rhansen** [comment]
With client-side code you can simply refresh after setting `"minify": false` and `"maxAge": 0` in your `settings.json`. For changes to server-side code you have to restart Etherpad.

**Comment by riedelcastro** [comment]
Thank you!
